ALTER TABLE daily_checkins
  ADD COLUMN IF NOT EXISTS answers JSONB NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS question_set JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS answered_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
